datasource:
  core:
    host: localhost
    port: 5432
    schema: tenants
    username: postgres
    password: password
  common:
    protocol: "jdbc"
    subprotocol: postgresql
    driverclass_name: org.postgresql.Driver
transfer:
  flows:
    - name: binx_hct_inst_credit_transfer_debtor_process
      direction: OUTGOING
      transformers:
        - field: transactionId
          variable_name: internalCorrelationId
        - field: payeeDfspId
          variable_name: originalPain001
          json_path: $.Document.PaymentInformation[0].CreditTransferTransactionInformation[0].CreditorAgent.FinancialInstitutionIdentification.BICFI
        - field: payeePartyId
          variable_name: originalPain001
          json_path: $.Document.PaymentInformation[0].CreditTransferTransactionInformation[0].CreditorAccount.Identification.IBAN
        - field: payeePartyIdType
          constant: IBAN
        - field: payerDfspId
          variable_name: originalPain001
          json_path: $.Document.PaymentInformation[0].DebtorAgent.FinancialInstitutionIdentification.BICFI
        - field: payerPartyId
          variable_name: debtorIban
        - field: payerPartyIdType
          constant: IBAN
        - field: payerFee
          variable_name: transactionFeeAmount
        - field: payerFeeCurrency
          variable_name: currency
        - field: amount
          variable_name: amount
        - field: currency
          variable_name: currency
        - field: direction
          constant: OUTGOING
        - field: endToEndIdentification
          variable_name: originalPain001
          json_path: $.Document.PaymentInformation[0].CreditTransferTransactionInformation[0].PaymentIdentification.EndToEndIdentification
        - field: paymentStatus
          variable_name: paymentStatus
    - name: binx_hct_inst_credit_transfer_creditor_process
      direction: INCOMING
      transformers:
        - field: transactionId
          variable_name: internalCorrelationId
        - field: payeeDfspId
          variable_name: originalPacs008
          xpath: /SendCreditTransferRequest/FIToFICstmrCdtTrf/CdtTrfTxInf/CdtrAgt/FinInstnId/BIC
        - field: payeePartyId
          variable_name: creditorIban
        - field: payeePartyIdType
          constant: IBAN
        - field: payerDfspId
          variable_name: originalPacs008
          xpath: /SendCreditTransferRequest/FIToFICstmrCdtTrf/CdtTrfTxInf/DbtrAgt/FinInstnId/BIC
        - field: payerPartyId
          variable_name: originalPacs008
          xpath: /SendCreditTransferRequest/FIToFICstmrCdtTrf/CdtTrfTxInf/DbtrAcct/Id/IBAN
        - field: payerPartyIdType
          constant: IBAN
        - field: amount
          variable_name: amount
        - field: currency
          variable_name: currency
        - field: endToEndIdentification
          variable_name: originalPacs008
          xpath: /SendCreditTransferRequest/FIToFICstmrCdtTrf/CdtTrfTxInf/PmtId/EndToEndId
        - field: paymentStatus
          variable_name: paymentStatus
    - name: binx_ig2_credit_transfer_debtor_process
      direction: OUTGOING
      transformers:
        - field: transactionId
          variable_name: internalCorrelationId
        - field: payeeDfspId
          variable_name: originalPain001
          json_path: $.Document.PaymentInformation[0].CreditTransferTransactionInformation[0].CreditorAgent.FinancialInstitutionIdentification.BICFI
        - field: payeePartyId
          variable_name: originalPain001
          json_path: $.Document.PaymentInformation[0].CreditTransferTransactionInformation[0].CreditorAccount.Identification.IBAN
        - field: payeePartyIdType
          constant: IBAN
        - field: payerDfspId
          variable_name: originalPain001
          json_path: $.Document.PaymentInformation[0].DebtorAgent.FinancialInstitutionIdentification.BICFI
        - field: payerPartyId
          variable_name: debtorIban
        - field: payerPartyIdType
          constant: IBAN
        - field: payerFee
          variable_name: transactionFeeAmount
        - field: payerFeeCurrency
          variable_name: currency
        - field: amount
          variable_name: amount
        - field: currency
          variable_name: currency
        - field: endToEndIdentification
          variable_name: originalPain001
          json_path: $.Document.PaymentInformation[0].CreditTransferTransactionInformation[0].PaymentIdentification.EndToEndIdentification
        - field: paymentStatus
          variable_name: paymentStatus
    - name: binx_ig2_credit_transfer_creditor_process
      direction: INCOMING
      transformers:
        - field: transactionId
          variable_name: internalCorrelationId
        - field: payeeDfspId
          variable_name: originalPacs008
          xpath: /Document/FIToFICstmrCdtTrf/CdtTrfTxInf/CdtrAgt/FinInstnId/BIC
        - field: payeePartyId
          variable_name: creditorIban
        - field: payeePartyIdType
          constant: IBAN
        - field: payerDfspId
          variable_name: originalPacs008
          xpath: /Document/FIToFICstmrCdtTrf/CdtTrfTxInf/DbtrAgt/FinInstnId/BIC
        - field: payerPartyId
          variable_name: originalPacs008
          xpath: /Document/FIToFICstmrCdtTrf/CdtTrfTxInf/DbtrAcct/Id/IBAN
        - field: payerPartyIdType
          constant: IBAN
        - field: amount
          variable_name: amount
        - field: currency
          variable_name: currency
        - field: endToEndIdentification
          variable_name: originalPacs008
          xpath: /Document/FIToFICstmrCdtTrf/CdtTrfTxInf/PmtId/EndToEndId
        - field: paymentStatus
          variable_name: paymentStatus
    - name: binx_onus_credit_transfer
      direction: OUTGOING
      transformers:
        - field: transactionId
          variable_name: internalCorrelationId
        - field: payeeDfspId
          variable_name: originalPain001
          json_path: $.Document.PaymentInformation[0].CreditTransferTransactionInformation[0].CreditorAgent.FinancialInstitutionIdentification.BICFI
        - field: payeePartyId
          variable_name: creditorIban
        - field: payeePartyIdType
          constant: IBAN
        - field: payerDfspId
          variable_name: originalPain001
          json_path: $.Document.PaymentInformation[0].DebtorAgent.FinancialInstitutionIdentification.BICFI
        - field: payerPartyId
          variable_name: debtorIban
        - field: payerPartyIdType
          constant: IBAN
        - field: payerFee
          variable_name: transactionFeeAmount
        - field: payerFeeCurrency
          variable_name: currency
        - field: amount
          variable_name: amount
        - field: currency
          variable_name: currency
        - field: paymentStatus
          variable_name: paymentStatus
    - name: binx_hct_inst_incoming_recall
      direction: INCOMING
      transformers:
        - field: transactionId
          variable_name: internalCorrelationId
        - field: payeeDfspId
          variable_name: generatedPacs004
          xpath: /SendPaymentReturnRequest/PmtRtr/TxInf/OrgnlTxRef/DbtrAgt/FinInstnId/BIC
        - field: payeePartyId
          variable_name: generatedPacs004
          xpath: /SendPaymentReturnRequest/PmtRtr/TxInf/OrgnlTxRef/DbtrAcct/Id/IBAN
        - field: payeePartyIdType
          constant: IBAN
        - field: payerDfspId
          variable_name: generatedPacs004
          xpath: /SendPaymentReturnRequest/PmtRtr/TxInf/OrgnlTxRef/CdtrAgt/FinInstnId/BIC
        - field: payerPartyId
          variable_name: debtorIban
        - field: payerPartyIdType
          constant: IBAN
        - field: amount
          variable_name: amount
        - field: currency
          variable_name: currency
        - field: endToEndIdentification
          variable_name: camt056
          xpath: /SendRequestForPaymentCancellationRequest/FIToFIPmtCxlReq/Undrlyg/TxInf/OrgnlEndToEndId
        - field: recallStatus
          variable_name: recallStatus
        - field: recallDirection
          constant: "HCT_INST.incoming.recall"
        - field: paymentStatus
          variable_name: paymentStatus
    - name: binx_hct_inst_outgoing_recall
      direction: OUTGOING
      transformers:
        - field: transactionId
          variable_name: internalCorrelationId
        - field: payeeDfspId
          variable_name: pacs004
          xpath: /SendPaymentReturnRequest/PmtRtr/TxInf/OrgnlTxRef/DbtrAgt/FinInstnId/BIC
        - field: payeePartyId
          variable_name: creditorIban
        - field: payeePartyIdType
          constant: IBAN
        - field: payerDfspId
          variable_name: pacs004
          xpath: /SendPaymentReturnRequest/PmtRtr/TxInf/OrgnlTxRef/CdtrAgt/FinInstnId/BIC
        - field: payerPartyId
          variable_name: pacs004
          xpath: /SendPaymentReturnRequest/PmtRtr/TxInf/OrgnlTxRef/CdtrAcct/Id/IBAN
        - field: payerPartyIdType
          constant: IBAN
        - field: amount
          variable_name: amount
        - field: currency
          variable_name: currency
        - field: endToEndIdentification
          variable_name: generatedCamt056
          xpath: /SendRequestForPaymentCancellationRequest/FIToFIPmtCxlReq/Undrlyg/TxInf/OrgnlEndToEndId
        - field: recallStatus
          variable_name: recallStatus
        - field: recallDirection
          constant: "HCT_INST.outgoing.recall"
        - field: paymentStatus
          variable_name: paymentStatus
    - name: binx_ig2_incoming_recall
      direction: INCOMING
      transformers:
        - field: transactionId
          variable_name: internalCorrelationId
        - field: payeeDfspId
          variable_name: pacs004
          xpath: /Document/PmtRtr/TxInf/OrgnlTxRef/DbtrAgt/FinInstnId/BIC
        - field: payeePartyId
          variable_name: pacs004
          xpath: /Document/PmtRtr/TxInf/OrgnlTxRef/DbtrAcct/Id/IBAN
        - field: payeePartyIdType
          constant: IBAN
        - field: payerDfspId
          variable_name: pacs004
          xpath: /Document/PmtRtr/TxInf/OrgnlTxRef/CdtrAgt/FinInstnId/BIC
        - field: payerPartyId
          variable_name: debtorIban
        - field: payerPartyIdType
          constant: IBAN
        - field: amount
          variable_name: amount
        - field: currency
          variable_name: currency
        - field: endToEndIdentification
          variable_name: camt056
          xpath: /Document/FIToFIPmtCxlReq/Undrlyg/TxInf/OrgnlEndToEndId
        - field: recallStatus
          variable_name: recallStatus
        - field: recallDirection
          constant: "IG2.incoming.recall"
        - field: paymentStatus
          variable_name: paymentStatus
    - name: binx_ig2_outgoing_recall
      direction: OUTGOING
      transformers:
        - field: transactionId
          variable_name: internalCorrelationId
        - field: payeeDfspId
          variable_name: pacs004
          xpath: /Document/PmtRtr/TxInf/OrgnlTxRef/DbtrAgt/FinInstnId/BIC
        - field: payeePartyId
          variable_name: creditorIban
        - field: payeePartyIdType
          constant: IBAN
        - field: payerDfspId
          variable_name: pacs004
          xpath: /Document/PmtRtr/TxInf/OrgnlTxRef/CdtrAgt/FinInstnId/BIC
        - field: payerPartyId
          variable_name: pacs004
          xpath: /Document/PmtRtr/TxInf/OrgnlTxRef/CdtrAcct/Id/IBAN
        - field: payerPartyIdType
          constant: IBAN
        - field: amount
          variable_name: amount
        - field: currency
          variable_name: currency
        - field: endToEndIdentification
          variable_name: camt056
          xpath: /Document/FIToFIPmtCxlReq/Undrlyg/TxInf/OrgnlEndToEndId
        - field: recallStatus
          variable_name: recallStatus
        - field: recallDirection
          constant: "IG2.outgoing.recall"
        - field: paymentStatus
          variable_name: paymentStatus
