kafka:
  msk: true
  brokers: "b-2.baasflowdev.6555wo.c8.kafka.eu-central-1.amazonaws.com:9098,b-1.baasflowdev.6555wo.c8.kafka.eu-central-1.amazonaws.com:9098,b-3.baasflowdev.6555wo.c8.kafka.eu-central-1.amazonaws.com:9098"
  consumer-group: ch1
  commit-interval-ms: 1000

importer:
  kafka:
    topic: "zeebe-export"
    reset: true
    aggreation-window-seconds: 2

spring:
  jpa:
    show-sql: false
    properties:
      eclipselink:
        logging:
          level: "INFO"
          parameters: true
          session: true
          thread: true
          timestamp: true
          logger: "hu.dpc.phee.operator.config.EclipselinkLogger"
    open-in-view: false

datasource:
  common:
    protocol: "jdbc"
    subprotocol: "mysql"
    driverclass_name: "com.mysql.cj.jdbc.Driver"
  core:
    port: 3306
    host: "operationsmysql"
    schema: "tenants"
    username: "mifos"
    password: "password"

server:
  port: 8000

application:
  bucket-name: paymenthub-ee-dev

cloud:
  aws:
    enabled: true
    credentials:
      access-key: ${AWS_ACCESS_KEY:AKIAX32JM37TZOJ5AKFB}
      secret-key: ${AWS_SECRET_KEY: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}
    region:
      static: us-east-2

